name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'
          cache: true
      
      - name: Install dependencies
        run: go mod download

      - name: Format check
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          make format
      
      - name: Lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          make lint

      - name: Run tests
        run: make test

      - name: Build
        run: make build 